language: objective-c
os: osx
osx_image: xcode11
script:
        - echo Install Cocoapods
        - gem install cocoapods

        - echo Install Example pod dependence
        - pod install --repo-update --project-directory=Example

        - echo Build Example project
        - xcodebuild -quiet -workspace Example/DemoApplication.xcworkspace -scheme DemoApplication -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
