name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: pod install --project-directory=Example

      - name: Build Example Project
        run: |
          xcodebuild clean build \
            -workspace Example/DemoApplication.xcworkspace \
            -scheme DemoApplication \
            -configuration Release CODE_SIGN_IDENTITY=- \
            -sdk iphonesimulator | xcpretty

      - name: Lint Pod
        run: pod lib lint --allow-warnings --sources=https://github.com/ElfSundae/CocoaPods-Specs.git,trunk --skip-import-validation
